project_id = "fsfspsydntutwftdihih"

[functions.generate-content]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = false

[functions.admin-user-actions]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false

[functions.user-ai-config]
verify_jwt = false